// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uuxmhrkxyidftcjsywvn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InV1eG1ocmt4eWlkZnRjanN5d3ZuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzYxNTUwMTYsImV4cCI6MjA5MTczMTAxNn0.LR1G-PTyFEjPFJFNBqGKsqnlQborP3TGWvd5b4UOuZs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});